# Generated by Django 5.2.5 on 2025-08-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0003_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='remainderapp.doctor')),
            ],
        ),
    ]
