# Generated by Django 5.2.5 on 2025-09-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0004_meetinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='last_met',
            new_name='lastMet',
        ),
    ]
