# Generated by Django 5.2.5 on 2025-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0005_rename_last_met_doctor_lastmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='lastMet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
