# Generated by Django 5.2.5 on 2025-09-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0006_alter_doctor_lastmet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
