# Generated by Django 5.2.5 on 2025-09-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remainderapp', '0007_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
